behaviors:
  Stand:
    trainer_type: ppo

    hyperparameters:
      batch_size: 2048 #2048
      buffer_size: 20480 #20480
      learning_rate: 0.0002                      # (0.0003)        [0.00001, 0.001]   
      learning_rate_schedule: linear
      beta: 0.005 #0.008                          # (0.005)         [0.0001, 0.01]  - may only be usefull for discreet action space
      epsilon: 0.2 #0.15                          # (0.2)           [0.1, 0.3]
      lambd: 0.95                                 # (0.95)          [0.90, 0.95]
      num_epoch: 3

    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 512
      num_layers: 3

    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.995 #0.8

      # curiosity:
      #   strength: 0.08                           # [0.001, 0.1]
      #   gamma: 0.99
      #   encoding_size: 256
      #   learning_rate: 1.0e-5

    max_steps: 50e6
    time_horizon: 512
    summary_freq: 50000
    keep_checkpoints: 5
    checkpoint_interval: 500000
    threaded: false
    init_path: null

engine_settings:
  width: 84
  height: 84
  quality_level: 0
  time_scale: 10
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: true