behaviors:
  Stand:
    trainer_type: ppo

    hyperparameters:
      # Hyperparameters common to PPO and SAC
      batch_size: 4096
      buffer_size: 40960
      learning_rate: 0.0001                       # (0.0003)    -     [0.00001, 0.001]   
      learning_rate_schedule: linear

      # PPO-specific hyperparameters
      # Replaces the "PPO-specific hyperparameters" section above
      beta: 0.005
      beta_schedule: constant
      epsilon: 0.2
      epsilon_schedule: linear
      lambd: 0.95
      num_epoch: 3

    # Configuration of the neural network (common to PPO/SAC)
    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 512
      num_layers: 3

      # # memory
      # memory:
      #   sequence_length: 64
      #   memory_size: 256

    # Trainer configurations common to all trainers
    max_steps: 50.0e6
    time_horizon: 256
    summary_freq: 10000
    keep_checkpoints: 5
    checkpoint_interval: 500000
    threaded: true
    init_path: null

    reward_signals:
      # environment reward (default)
      extrinsic:
        strength: 1.0
        gamma: 0.8

      # curiosity module
      curiosity:
        strength: 0.08
        gamma: 0.99
        encoding_size: 256
        learning_rate: 1.0e-5

engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 5
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: true